# Generated by Django 5.2.13 on 2026-04-24 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=100, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name_fa'],
            },
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=100, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name_fa'],
            },
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('bio_fa', models.TextField(blank=True)),
                ('bio_en', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='singers/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('price', models.PositiveIntegerField(default=50000)),
                ('original_file', models.FileField(help_text='فایل اصلی آهنگ مشهور (فقط برای ادمین)', upload_to='originals/')),
                ('instrumental_file', models.FileField(help_text='فایل بی\u200cکلام فروشی', upload_to='instrumentals/')),
                ('sample_file', models.FileField(help_text='نمونه ۳۰ ثانیه\u200cای', upload_to='samples/')),
                ('cover_image', models.ImageField(upload_to='covers/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sales_count', models.PositiveIntegerField(default=0)),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='shop.genre')),
                ('mood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='shop.mood')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='shop.singer')),
            ],
        ),
    ]
