"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-cv=7z@o)jk60mxp#(sv4h2^mui7bitz1pdnef^%1@09wjyrlqg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'shop',
    'accounts',
    'payment',
    'storages', # ArvanCloud Storage S3
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    # برای استفاده کردن از middleware and apikey گزینه زیر باید فعال باشه
    # 'api.middleware.APIKeyMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'db_onritm',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {'charset': 'utf8mb4'},
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'accounts.User'
# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MEDIA_URL = '/media/'
# در حالت اجرای باید تغییر داده شود
MEDIA_ROOT = BASE_DIR / 'media'

# برای دسترسی به فایل‌های محافظت شده (اختیاری)
PROTECTED_MEDIA_ROOT = BASE_DIR / 'protected_media'

# ============================================
# ArvanCloud S3-like Object Storage Settings
# ============================================

# اطلاعات دسترسی به آرون
AWS_ACCESS_KEY_ID = 'f28d69d6-99f5-4188-ad79-8e8741f4320d'          # کلید دسترسی آرون
AWS_SECRET_ACCESS_KEY = 'e5a24dd622395f5401194ea5951601ccef26b5a3929bfc12a2655e47b222a024'      # کلید مخفی آرون
AWS_STORAGE_BUCKET_NAME = 'onritm-media'  # نام باکتت روی آرون

# تنظیمات منطقه و آدرس endpoint - حتماً بر اساس منطقه باکتی که ساختی!
AWS_S3_REGION_NAME = 'ir-tbz-sh1'          # منطقه تهران
AWS_S3_ENDPOINT_URL = 'https://s3.ir-tbz-sh1.arvanstorage.ir'   # آدرس endpoint آرون

# تنظیمات امنیتی
AWS_QUERYSTRING_AUTH = False   # این رو False بذار تا URLهایی که ساخته می‌شن کلید نداشته باشن؛ خودمون جداگانه لینک امن می‌سازیم

# زمان منقضی شدن لینک دانلود (بر حسب ثانیه) - برای فایل‌های خصوصی استفاده میشه
AWS_QUERYSTRING_EXPIRE = 3600  # 1 ساعت (یا هر مقداری که خودت صلاح می‌دونی)


# ============================================
# ArvanCloud S3-like Object Storage Backends
# ============================================

# تنظیمات پیش‌فرض جنگو برای ذخیره‌سازی فایل‌ها
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.InMemoryStorage", # برای کش کردن موقتی فایل‌ها
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# کلاس‌های استوریج سفارشی برای فایل‌های عمومی و خصوصی
DEFAULT_FILE_STORAGE = 'storage_backends.PublicMediaStorage' # برای فیلدهایی که استوریج خاصی براشون تعریف نکردیم (مثلاً کاور)
PRIVATE_FILE_STORAGE = 'storage_backends.PrivateMediaStorage' # برای فایل‌های خصوصی (فایل اصلی MP3)

# تنظیمات CORS برای ارتباط با Next.js
CORS_ALLOW_ALL_ORIGINS = True  # فقط برای توسعه
# یا برای تولید:
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:5500",
    "https://yourdomain.com",
]
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    # آدرس سایت شما در هاست
]

API_SECRET_KEY = 'sinarahmani123456789'

# تنظیمات DRF
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 12,
}

# تنظیمات JWT (اختیاری، می‌توانید زمان انقضا و ... را تنظیم کنید)
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# تنظیمات sms.ir (از پنل خودت دریافت کن)
SMS_IR_API_KEY = 'pWZFBzaFeQxIU3DQNgGqN9akHR0nPEW1BDxCVRNaBL32VHIl'

# تنظیمات زرین پال
ZARINPAL_CONFIG = {
    "MERCHANT_ID": "f61e1794-23aa-4367-adf9-b37b3f56fa9f",
    "REQUEST_URL": "https://sandbox.zarinpal.com/pg/v4/payment/request.json",
    "VERIFY_URL": "https://sandbox.zarinpal.com/pg/v4/payment/verify.json",
    "STARTPAY_URL": "https://sandbox.zarinpal.com/pg/StartPay/",
    # "REQUEST_URL": "https://api.zarinpal.com/pg/v4/payment/request.json",
    # "VERIFY_URL": "https://api.zarinpal.com/pg/v4/payment/verify.json",
    # "STARTPAY_URL": "https://www.zarinpal.com/pg/StartPay/",
}

